"""change attrs original, short

Revision ID: fd0b25f693df
Revises: 64b9fa736b46
Create Date: 2022-09-01 17:05:17.532410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0b25f693df'
down_revision = '64b9fa736b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_URL_map_timestamp', table_name='URL_map')
    op.create_index(op.f('ix_URL_map_original'), 'URL_map', ['original'], unique=False)
    op.create_index(op.f('ix_URL_map_short'), 'URL_map', ['short'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_URL_map_short'), table_name='URL_map')
    op.drop_index(op.f('ix_URL_map_original'), table_name='URL_map')
    op.create_index('ix_URL_map_timestamp', 'URL_map', ['timestamp'], unique=False)
    # ### end Alembic commands ###
